docker build -t hadoop-base hadoop
docker build -t hadoop-namenode namenode
docker build -t hadoop-datanode datanode
docker build -t hadoop-resourcemanager resourcemanager
docker build -t hadoop-nodemanager nodemanager
docker build -t hadoop-historyserver historyserver
docker build -t hadoop-spark spark
docker build -t hadoop-sparkmaster sparkmaster
docker build -t hadoop-sparkworker sparkworker